Load Dataset

In [26]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    "C:\\Users\\aishw\\SAR-Student-Success-Retention\\datasets\\student_success_dataset_30000.csv"
)
print("Shape:", df.shape)
df.head()

Shape: (30000, 70)

,student_id,department,specialization,current_year,semester,gender,cgpa,semester_gpa,cgpa_trend,backlog_count,...,stress_score,time_management_score,consistency_score,academic_risk_band,dropout_risk_band,placement_risk_band,recommended_intervention,recommended_career_path,recommended_certification,recommended_course_track
0,STU202600001,Computer Engineering,Full Stack Development,Third Year,6,Male,9.00,9.15,Stable,1,...,62.52,61.18,75.33,Low,Low,Medium,Routine Academic Mentoring & Growth Tracking,IT Systems Consultant,Project Management Professional (PMP) Baseline,Academic Support & Catch-Up Track
1,STU202600002,Civil Engineering,Environmental Engineering,Second Year,3,Female,8.25,8.31,Stable,0,...,34.62,59.95,63.80,Low,Low,High,Routine Academic Mentoring & Growth Tracking,Structural & Infrastructure Planner,Project Management Professional (PMP) Baseline,Entrepreneurship Track
2,STU202600003,AI & ML,Computer Vision,Final Year,7,Female,8.81,8.79,Stable,0,...,34.43,74.90,91.29,Low,Low,Low,Routine Academic Mentoring & Growth Tracking,AI/ML Research Specialist,AWS Certified Machine Learning Specialty,Placement Fast Track
3,STU202600004,Electronics & Telecommunication,Embedded Systems,First Year,2,Male,8.83,8.69,Stable,0,...,32.98,72.21,88.28,Low,Low,High,Routine Academic Mentoring & Growth Tracking,Embedded Systems & IoT Engineer,PTC IoT Developer Certification,Academic Support & Catch-Up Track
4,STU202600005,Mechanical Engineering,CAD/CAM,Third Year,6,Male,9.34,9.36,Stable,0,...,45.71,74.01,87.37,Low,Low,Low,Routine Academic Mentoring & Growth Tracking,Product Design Engineer,Project Management Professional (PMP) Baseline,Placement Fast Track

In [27]:

print("Shape:", df.shape)
df.head()

Shape: (30000, 70)

,student_id,department,specialization,current_year,semester,gender,cgpa,semester_gpa,cgpa_trend,backlog_count,...,stress_score,time_management_score,consistency_score,academic_risk_band,dropout_risk_band,placement_risk_band,recommended_intervention,recommended_career_path,recommended_certification,recommended_course_track
0,STU202600001,Computer Engineering,Full Stack Development,Third Year,6,Male,9.00,9.15,Stable,1,...,62.52,61.18,75.33,Low,Low,Medium,Routine Academic Mentoring & Growth Tracking,IT Systems Consultant,Project Management Professional (PMP) Baseline,Academic Support & Catch-Up Track
1,STU202600002,Civil Engineering,Environmental Engineering,Second Year,3,Female,8.25,8.31,Stable,0,...,34.62,59.95,63.80,Low,Low,High,Routine Academic Mentoring & Growth Tracking,Structural & Infrastructure Planner,Project Management Professional (PMP) Baseline,Entrepreneurship Track
2,STU202600003,AI & ML,Computer Vision,Final Year,7,Female,8.81,8.79,Stable,0,...,34.43,74.90,91.29,Low,Low,Low,Routine Academic Mentoring & Growth Tracking,AI/ML Research Specialist,AWS Certified Machine Learning Specialty,Placement Fast Track
3,STU202600004,Electronics & Telecommunication,Embedded Systems,First Year,2,Male,8.83,8.69,Stable,0,...,32.98,72.21,88.28,Low,Low,High,Routine Academic Mentoring & Growth Tracking,Embedded Systems & IoT Engineer,PTC IoT Developer Certification,Academic Support & Catch-Up Track
4,STU202600005,Mechanical Engineering,CAD/CAM,Third Year,6,Male,9.34,9.36,Stable,0,...,45.71,74.01,87.37,Low,Low,Low,Routine Academic Mentoring & Growth Tracking,Product Design Engineer,Project Management Professional (PMP) Baseline,Placement Fast Track

Basic Information

In [28]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 70 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     30000 non-null  object
 1   department                     30000 non-null  object
 2   specialization                 30000 non-null  object
 3   current_year                   30000 non-null  object
 4   semester                       30000 non-null  int64
 5   gender                         30000 non-null  object
 6   cgpa                           30000 non-null  float64
 7   semester_gpa                   30000 non-null  float64
 8   cgpa_trend                     30000 non-null  object
 9   backlog_count                  30000 non-null  int64
 10  internal_marks_avg             30000 non-null  float64
 11  assignment_submission_rate     30000 non-null  float64
 12  lab_performance_score          30000 non-null  float64
 13  project_score                  30000 non-null  float64
 14  academic_risk_score            30000 non-null  float64
 15  attendance_percentage          30000 non-null  float64
 16  classes_missed                 30000 non-null  int64
 17  attendance_trend               30000 non-null  object
 18  lms_login_frequency            30000 non-null  int64
 19  course_completion_rate         30000 non-null  float64
 20  video_watch_percentage         30000 non-null  float64
 21  quiz_attempt_rate              30000 non-null  float64
 22  study_hours_per_week           30000 non-null  int64
 23  club_participation_score       30000 non-null  float64
 24  hackathon_count                30000 non-null  int64
 25  technical_event_participation  30000 non-null  int64
 26  leadership_score               30000 non-null  float64
 27  extracurricular_score          30000 non-null  float64
 28  fee_delay_days                 30000 non-null  int64
 29  scholarship_status             30000 non-null  object
 30  financial_stress_score         30000 non-null  float64
 31  mentor_meetings_count          30000 non-null  int64
 32  mentor_feedback_score          30000 non-null  float64
 33  intervention_history_count     30000 non-null  int64
 34  counseling_sessions            30000 non-null  int64
 35  communication_score            30000 non-null  float64
 36  presentation_score             30000 non-null  float64
 37  teamwork_score                 30000 non-null  float64
 38  coding_score                   30000 non-null  float64
 39  aptitude_score                 30000 non-null  float64
 40  problem_solving_score          30000 non-null  float64
 41  database_score                 30000 non-null  float64
 42  web_development_score          30000 non-null  float64
 43  ai_ml_score                    30000 non-null  float64
 44  cloud_score                    30000 non-null  float64
 45  cybersecurity_score            30000 non-null  float64
 46  linkedin_profile_score         30000 non-null  float64
 47  resume_score                   30000 non-null  float64
 48  github_activity_score          30000 non-null  float64
 49  portfolio_score                30000 non-null  float64
 50  certification_count            30000 non-null  int64
 51  career_readiness_score         30000 non-null  float64
 52  mock_interview_score           30000 non-null  float64
 53  group_discussion_score         30000 non-null  float64
 54  placement_readiness_score      30000 non-null  float64
 55  placement_probability          30000 non-null  float64
 56  internship_count               30000 non-null  int64
 57  industry_project_count         30000 non-null  int64
 58  open_source_contributions      30000 non-null  int64
 59  motivation_score               30000 non-null  float64
 60  stress_score                   30000 non-null  float64
 61  time_management_score          30000 non-null  float64
 62  consistency_score              30000 non-null  float64
 63  academic_risk_band             30000 non-null  object
 64  dropout_risk_band              30000 non-null  object
 65  placement_risk_band            30000 non-null  object
 66  recommended_intervention       30000 non-null  object
 67  recommended_career_path        30000 non-null  object
 68  recommended_certification      30000 non-null  object
 69  recommended_course_track       30000 non-null  object
dtypes: float64(40), int64(15), object(15)
memory usage: 16.0+ MB
None

Missing Values Check

In [29]:
missing = df.isnull().sum()

missing[missing > 0]

Series([], dtype: int64)

Duplicate Check

In [30]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

Risk Distribution

In [31]:
print(df["academic_risk_band"].value_counts())

print("\n")

print(df["dropout_risk_band"].value_counts())

print("\n")

print(df["placement_risk_band"].value_counts())

academic_risk_band
Low         24390
Medium       3754
High         1691
Critical      165
Name: count, dtype: int64


dropout_risk_band
Low         24157
Medium       5042
High          789
Critical       12
Name: count, dtype: int64


placement_risk_band
High        14012
Low          7667
Medium       7125
Critical     1196
Name: count, dtype: int64

Feature Statistics

In [32]:
df[
    [
        "cgpa",
        "attendance_percentage",
        "backlog_count",
        "coding_score",
        "stress_score",
        "placement_probability"
    ]
].describe()

,cgpa,attendance_percentage,backlog_count,coding_score,stress_score,placement_probability
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000
mean,8.314517,86.875339,0.556400,68.920448,48.235903,47.125413
std,0.775800,6.787769,0.994243,15.706217,16.297828,19.469175
min,5.420000,58.330000,0.000000,15.000000,5.000000,4.910000
25%,7.780000,82.290000,0.000000,58.690000,36.820000,31.340000
50%,8.360000,87.100000,0.000000,69.920000,46.820000,39.560000
75%,8.890000,91.840000,1.000000,80.182500,57.980000,65.350000
max,10.000000,100.000000,4.000000,100.000000,100.000000,96.610000

Correlation Check

In [33]:
cols = [
    "cgpa",
    "attendance_percentage",
    "backlog_count",
    "stress_score",
    "coding_score",
    "placement_probability",
    "career_readiness_score"
]

df[cols].corr()

,cgpa,attendance_percentage,backlog_count,stress_score,coding_score,placement_probability,career_readiness_score
cgpa,1.000000,0.755820,-0.228428,-0.240538,0.277732,0.349814,0.289988
attendance_percentage,0.755820,1.000000,-0.205212,-0.254407,0.248233,0.286216,0.253128
backlog_count,-0.228428,-0.205212,1.000000,0.632477,-0.063122,-0.381479,-0.074920
stress_score,-0.240538,-0.254407,0.632477,1.000000,-0.072349,-0.271679,-0.082781
coding_score,0.277732,0.248233,-0.063122,-0.072349,1.000000,0.203676,0.363728
placement_probability,0.349814,0.286216,-0.381479,-0.271679,0.203676,1.000000,0.189755
career_readiness_score,0.289988,0.253128,-0.074920,-0.082781,0.363728,0.189755,1.000000

In [34]:
df[
    [
        "academic_risk_score",
        "academic_risk_band"
    ]
].sample(20)

       academic_risk_score academic_risk_band
25171                 7.96                Low
24396                22.13                Low
8359                 51.79             Medium
1851                 10.60                Low
23285                13.79                Low
24821                10.77                Low
6320                 14.49                Low
2410                  7.73                Low
8416                  1.99                Low
15125                20.19                Low
1803                  3.35                Low
22994                10.84                Low
25580                 8.93                Low
7858                 11.29                Low
1589                 14.40                Low
19577                42.41             Medium
19391                25.78                Low
14175                22.47                Low
15248                50.90             Medium
698                  25.99                Low

In [35]:
df.groupby("academic_risk_band")["academic_risk_score"].describe()

,count,mean,std,min,25%,50%,75%,max
academic_risk_band,,,,,,,,
Critical,165.0,83.194000,2.606185,80.00,81.300,82.39,84.2300,93.94
High,1691.0,69.683572,5.255303,60.04,65.435,69.81,73.6350,79.94
Low,24390.0,16.756690,7.729400,0.00,11.050,15.50,21.5000,35.00
Medium,3754.0,44.733474,6.855981,35.00,38.480,44.07,50.0625,59.98

In [36]:
df.groupby("placement_risk_band")["placement_probability"].describe()

,count,mean,std,min,25%,50%,75%,max
placement_risk_band,,,,,,,,
Critical,1196.0,16.352993,2.962961,4.91,14.46,17.05,18.755,20.00
High,14012.0,31.530166,4.888206,20.01,28.06,32.06,35.380,40.00
Low,7667.0,73.744952,5.878420,65.00,68.99,72.97,77.625,96.61
Medium,7125.0,54.315928,7.671429,40.00,48.04,55.91,60.970,65.00